# Generated by Django 5.0 on 2023-12-10 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.CharField(choices=[('한', '한강권역'), ('금', '금강권역'), ('영', '영섬권역'), ('낙', '낙동강권역')], max_length=10)),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=17)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('quality', models.PositiveSmallIntegerField()),
                ('quantity', models.FloatField()),
                ('luck', models.CharField(choices=[('대흉', '대흉'), ('흉', '흉'), ('평', '평'), ('길', '길'), ('대길', '대길')], max_length=10)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='stations.station')),
            ],
        ),
    ]
