# Generated by Django 5.0 on 2023-12-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='area',
        ),
    ]
